export { HomePage } from './Home'
export { DetailPage } from './Detail'
export { CategoryPhotosPage } from './CategoryPhotos'
export { FavsPage } from './Favs'
export { LoginPage } from './Login'
export { UserPage } from './User'
export { RegisterPage } from './Register'
